# Generated by Django 2.2.5 on 2019-11-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20191107_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(default='null@c.com', max_length=150)),
                ('token', models.CharField(default='null0', max_length=50)),
            ],
        ),
    ]
