# Generated by Django 2.2.5 on 2019-10-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='event',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='player',
            name='events',
        ),
        migrations.RemoveField(
            model_name='player',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='AttendedEvent',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
