# Generated by Django 2.2.5 on 2019-10-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=100)),
                ('evento', models.ManyToManyField(to='Eventos.Evento')),
            ],
            options={
                'db_table': 'etiquetas',
            },
        ),
    ]
