# Generated by Django 2.2.5 on 2019-10-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='evento',
        ),
        migrations.AddField(
            model_name='direccion',
            name='evento',
            field=models.ManyToManyField(to='Eventos.Evento'),
        ),
    ]
