# Generated by Django 2.2.5 on 2019-11-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0006_auto_20191106_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsigStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Evento', models.IntegerField()),
                ('email_staff', models.EmailField(max_length=254)),
            ],
            options={
                'unique_together': {('id_Evento', 'email_staff')},
            },
        ),
    ]
