# Generated by Django 2.2.5 on 2019-11-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0007_asigstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='entidad',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_final',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora_final',
            field=models.TimeField(null=True),
        ),
    ]
