# Generated by Django 2.2.5 on 2019-11-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0008_auto_20191107_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='hora_de_inicio',
            field=models.TimeField(null=True),
        ),
    ]
