# Generated by Django 2.2.5 on 2019-11-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0009_auto_20191107_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='etiquetas',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
