# Generated by Django 2.2.5 on 2019-11-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0010_evento_etiquetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='regevento',
            name='confirmacion',
            field=models.CharField(default='No Confirmado', max_length=50, null=True),
        ),
    ]
