# Generated by Django 2.2.5 on 2019-11-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0011_regevento_confirmacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='direccion',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
