# Generated by Django 2.2.5 on 2019-11-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0012_evento_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='mostrar',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='periodicidad',
            field=models.CharField(default='', max_length=100),
        ),
    ]
