# Generated by Django 2.2.7 on 2019-11-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0013_auto_20191125_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='periodicidad',
            field=models.CharField(max_length=100),
        ),
    ]
